version: "3.9"

services:
    
    ecommerceweb:
        build: ./web
        image: "myimage:ecommerceweb"
        ports:
            - 80:80
            - 443:443
        links:
            - "ecommercedb:ecommercedb_container"
        container_name: "ecommerceweb_container"
        
    ecommercedb:
        build: ./db
        image: "myimage:ecommercedb"
        ports:
            - 4306:3306
        expose:
            - 3306
        container_name: "ecommercedb_container"
        volumes:
            - ecomercedb_data:/var/lib/mysql
            
volumes:
    ecomercedb_data:
            