version: "3.9"

services:
    
    web:
        build: ./web
        image: "myimage:web"
        ports:
            - 80:80
            - 443:443
        links:
            - "db:ecommercedb_container"
        container_name: "ecommerceweb_container"
        
    db:
        build: ./db
        image: "myimage:db"
        ports:
            - 4306:3306
        expose:
            - 3306
        container_name: "ecommercedb_container"
        volumes:
            - db_data:/var/lib/mysql
            
volumes:
    db_data:
            